const PlanData = [
  {
    name: "Clearvikalp Wellness Basic",
    title:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus,",
    amount: {
      withDiscount: "1399",
      withoutDiscount: "4000",
      discount: "65% off",
    },
    test: [
      "CBC",
      "Blood Group",
      "Urine Routine",
      "Hba1c",
      "RBS",
      "Serum Creatinine",
      "Bilirubin",
      "SGOT",
      "SGPT",
      "Serum Electrolytes",
      "Lipid Profile (HDL/LDL/Total chol/Triglyceride/VLDL)",
    ],
  },
  {
    name: "Clearvikalp Wellness Plus",
    title:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus,",
    amount: {
      withDiscount: "2999",
      withoutDiscount: "7555",
      discount: "61% off",
    },
    test: [
      "CBC",
      "ESR",
      "Blood Group",
      "Stool Routine",
      "Urine Routine",
      "Vit- B12",
      "Vit-D3",
      "FBS",
      "PPBS",
      "Serum Creatinine",
      "Lipid Profile (HDL/LDL/Total chol/Triglyceride/VLDL)",
      "Serum Electrolytes",
      "Serum Uric Acid",
      "BUN",
      "Albumin",
      "Alkaline Phosphatase",
      "Bilirubin",
      "GGTP",
      "Globulin",
      "SGOT",
      "SGPT",
      "Total Protein",
    ],
  },
  {
    name: "Clearvikalp Wellness Pro",
    title:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus,",
    amount: {
      withDiscount: "3499",
      withoutDiscount: "10500",
      discount: "67% off",
    },

    test: [
      "CBC",
      "ESR",
      "Blood Group",
      "Stool Routine",
      "Urine Routine",
      "Vit- B12",
      "Vit-D3",
      "Lipid Profile",
      "FBS",
      "PPBS",
      "Serum Creatinine",
      "Serum Electrolytes",
      "Serum Uric Acid",
      "BUN",
      "Thyroid",
      "Hba1c",
      "Hbsag",
      "HIV I & II",
      "Prostate Surface Antigen (PSA)",
      "Albumin",
      "Alkaline Phosphatase",
      "Bilirubin",
      "GGTP",
      "Globulin",
      "SGOT",
      "SGPT",
      "Total Protein",
    ],
  },
];

export default PlanData;
